// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Custom API Routes
 *
 * This file is the editable surface for custom backend logic that
 * doesn't fit the auto-generated CRUD model (per-model GET/POST/PATCH/
 * DELETE under `/api/<model>s`). Anything you mount on the exported
 * Hono app shows up at `/api/...` alongside the generated CRUD routes.
 *
 * Examples:
 *   - Aggregations / dashboards: `app.get('/dashboard', ...)`
 *   - Webhooks: `app.post('/webhooks/stripe', ...)`
 *   - Auth flows: `app.post('/auth/login', ...)`
 *
 * For installed integrations (Jira, Slack, Google, Meta Ads, etc.):
 *
 * - Dashboards / list views / "my X" pages → mount a route HERE that
 *   uses `getServerToolsClient()`. Resolve identity per request with
 *   `<TOOLKIT>_GET_CURRENT_USER`, compose the calls you need, return
 *   a clean shape your component owns.
 *
 *   The SDK auto-parses tool result `data` on success (the runtime
 *   JSON.stringifies tool responses; @shogo-ai/sdk/tools >=1.3 parses
 *   them back). Index `data` like a plain object — do NOT write a
 *   `JSON.parse(result.data)` helper. Pass a generic to `execute<T>()`
 *   for typed access.
 *
 *   import { getServerToolsClient } from '@shogo-ai/sdk/tools'
 *
 *   app.get('/jira/my-issues', async (c) => {
 *     const tools = getServerToolsClient()
 *     const me = await tools.execute<{ accountId: string }>('JIRA_GET_CURRENT_USER', {})
 *     if (!me.ok || !me.data?.accountId) {
 *       return c.json({ error: me.error ?? 'not authenticated' }, 401)
 *     }
 *     const issues = await tools.execute<{ issues: unknown[] }>('JIRA_SEARCH_ISSUES', {
 *       jql: `assignee = "${me.data.accountId}"`,
 *     })
 *     if (!issues.ok) return c.json({ error: issues.error ?? 'search failed' }, 502)
 *     return c.json({ issues: issues.data?.issues ?? [] })
 *   })
 *
 *   In the browser, surface the server's `error` field — never throw
 *   `new Error('Failed to load X')`:
 *
 *     const res = await fetch('/api/jira/my-issues')
 *     const body = await res.json().catch(() => ({}))
 *     if (!res.ok) setError(body.error ?? `HTTP ${res.status}`)
 *     else setIssues(body.issues ?? [])
 *
 *   After writing or editing a route, hit it to confirm shape + status:
 *     curl -s -w "\nHTTP %{http_code}\n" http://localhost:$RUNTIME_PORT/api/jira/my-issues
 *   A green build proves the file compiled, not that the endpoint works.
 *
 * - Ad-hoc interactive actions (button clicks, form submits) → use
 *   `useTools()` directly in the component. Don't add a route here for
 *   single-call passthroughs.
 *
 * Hand-rolling a `fetch()` to the provider's REST API will fail
 * because the pod has no provider tokens — auth lives in the runtime.
 * NEVER hardcode the agent operator's identity (accountId, member id,
 * userId) into route code; resolve it per request as shown above.
 *
 * The runtime watches this file. Saving triggers a fast restart of
 * `server.tsx` (no schema regeneration, no `prisma db push`) so changes
 * land in under a second.
 *
 * The Prisma client is available — import it from `./src/lib/db`:
 *
 *   import { prisma } from './src/lib/db'
 *
 *   app.get('/stats', async (c) => {
 *     const userCount = await prisma.user.count()
 *     return c.json({ userCount })
 *   })
 *
 * Do NOT edit `server.tsx` — it is auto-generated by the SDK from
 * `shogo.config.json` and will be overwritten on the next regeneration.
 */

import { Hono } from 'hono'
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { resolve } from 'path'

const app = new Hono()

const SHOPIFY_SCOPES = [
  'read_products',
  'write_products',
  'read_orders',
  'write_orders',
  'read_inventory',
  'write_inventory',
  'read_script_tags',
  'write_script_tags',
].join(',')

// ── Shopify OAuth: initiate ──────────────────────────────────────────
app.get('/shopify/auth', (c) => {
  const shop = process.env.SHOPIFY_STORE_DOMAIN
  const clientId = process.env.SHOPIFY_CLIENT_ID
  const redirectUri = process.env.SHOPIFY_REDIRECT_URI

  if (!shop || !clientId || !redirectUri) {
    return c.json({ error: 'Missing SHOPIFY_STORE_DOMAIN, SHOPIFY_CLIENT_ID, or SHOPIFY_REDIRECT_URI' }, 500)
  }

  const authUrl = new URL(`https://${shop}/admin/oauth/authorize`)
  authUrl.searchParams.set('client_id', clientId)
  authUrl.searchParams.set('scope', SHOPIFY_SCOPES)
  authUrl.searchParams.set('redirect_uri', redirectUri)

  return c.redirect(authUrl.toString())
})

// ── Shopify OAuth: callback ──────────────────────────────────────────
app.get('/shopify/oauth/callback', async (c) => {
  const { shop, code, hmac, state } = c.req.query()

  if (!shop || !code) {
    return c.json({ error: 'Missing shop or code parameter' }, 400)
  }

  const clientId = process.env.SHOPIFY_CLIENT_ID
  const clientSecret = process.env.SHOPIFY_CLIENT_SECRET

  if (!clientId || !clientSecret) {
    return c.json({ error: 'Missing SHOPIFY_CLIENT_ID or SHOPIFY_CLIENT_SECRET' }, 500)
  }

  // Exchange the authorization code for an access token
  const tokenRes = await fetch(`https://${shop}/admin/oauth/access_token`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      client_id: clientId,
      client_secret: clientSecret,
      code,
    }),
  })

  if (!tokenRes.ok) {
    const err = await tokenRes.text()
    return c.json({ error: `Token exchange failed: ${err}` }, 502)
  }

  const tokenData = (await tokenRes.json()) as {
    access_token: string
    refresh_token?: string
    scope: string
  }

  const scopes = tokenData.scope?.split(',').map((s) => s.trim()) ?? []

  // Save tokens to .env
  const envPath = resolve(import.meta.dir, '..', '.env')
  let envContent = existsSync(envPath) ? readFileSync(envPath, 'utf-8') : ''

  const vars: Record<string, string> = {
    SHOPIFY_ACCESS_TOKEN: tokenData.access_token,
    SHOPIFY_REFRESH_TOKEN: tokenData.refresh_token ?? '',
  }

  for (const [key, value] of Object.entries(vars)) {
    if (!value) continue
    const regex = new RegExp(`^${key}=.*$`, 'm')
    const line = `${key}=${value}`
    if (regex.test(envContent)) {
      envContent = envContent.replace(regex, line)
    } else {
      envContent = envContent.trim() + `\n${line}\n`
    }
  }

  writeFileSync(envPath, envContent, 'utf-8')

  return c.json({
    success: true,
    shop,
    scopes,
    has_refresh_token: !!tokenData.refresh_token,
    access_token: tokenData.access_token,
    refresh_token: tokenData.refresh_token ?? null,
    message: 'Tokens saved to .env. Rotate with: bun run scripts/shopify-token-rotate.ts',
  })
})

// Add your custom routes here. They mount under `/api/`.
// Example:
//   app.get('/hello', (c) => c.json({ message: 'Hello!' }))

export default app
